{% set name = "rich-cli" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e9a2bca579cf47fbd1b6bfc0f43b7d9e93b390b376114a66b5c4ea5a90296a9

build:
  noarch: python
  number: 0
  script_env: PYTHONUTF8=1
  entry_points:
    - rich = rich_cli.__main__:run
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - rich >=12.0.0
    - click >=8.0.0
    - requests >=2.0.0
    - textual >=0.1.15
    - rich-rst >=1.1.7

test:
  commands:
    - rich --help

about:
  home: https://github.com/Textualize/rich-cli
  summary: Rich-cli is a command line toolbox for fancy output in the terminal
  keywords: syntax-highlighting markdown terminal rich terminal-colors
  dev_url: https://github.com/Textualize/rich-cli
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
    - willmcgugan
