{% set name = "rich-cli" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 16992bcbd454974dc53671ba1a12e189148566164aaa7370bdf6648c8b1438c3

build:
  noarch: python
  number: 0
  script_env: PYTHONUTF8=1
  entry_points:
    - rich = rich_cli.__main__:run
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - rich >=12.4.0,<13.0.0
    - click >=8.0.0,<9.0.0
    - requests >=2.0.0,<3.0.0
    - textual >=0.1.18,<0.2.0
    - rich-rst >=1.1.7,<2.0.0

test:
  requires:
    - python {{ python_min }}
  commands:
    - rich --help

about:
  home: https://github.com/Textualize/rich-cli
  summary: Rich-cli is a command line toolbox for fancy output in the terminal
  keywords: syntax-highlighting markdown terminal rich terminal-colors
  dev_url: https://github.com/Textualize/rich-cli
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
    - willmcgugan
