{% set name = "rich-cli" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f99ed213fb18c25999b644335f74d2be621a3a68593359e7fc62e95fe7e9a8a

build:
  noarch: python
  number: 1
  script_env: PYTHONUTF8=1
  entry_points:
    - rich = rich_cli.__main__:run
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - rich >=12.0.0
    - click >=8.0.0
    - requests >=2.0.0
    - textual >=0.1.15
    - rich-rst >=1.1.7

test:
  requires:
    - python {{ python_min }}
  commands:
    - rich --help

about:
  home: https://github.com/Textualize/rich-cli
  summary: Rich-cli is a command line toolbox for fancy output in the terminal
  keywords: syntax-highlighting markdown terminal rich terminal-colors
  dev_url: https://github.com/Textualize/rich-cli
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
    - willmcgugan
